import fs from 'fs';
import path from 'path';

const rawData = [
  // Topic: People and family (1 - 41)
  { topic: "People and family", id: 1, noun: "der Mensch", plural: "Menschen", english: "person / human", pron: "dair muhnsh" },
  { topic: "People and family", id: 2, noun: "die Person", plural: "Personen", english: "person", pron: "dee pairson" },
  { topic: "People and family", id: 3, noun: "der Mann", plural: "Männer", english: "man / husband", pron: "dair mann" },
  { topic: "People and family", id: 4, noun: "die Frau", plural: "Frauen", english: "woman / wife", pron: "dee frow" },
  { topic: "People and family", id: 5, noun: "das Kind", plural: "Kinder", english: "child", pron: "das kind" },
  { topic: "People and family", id: 6, noun: "das Baby", plural: "Babys", english: "baby", pron: "das baby" },
  { topic: "People and family", id: 7, noun: "der Junge", plural: "Jungen", english: "boy", pron: "dair yunguh" },
  { topic: "People and family", id: 8, noun: "das Mädchen", plural: "Mädchen", english: "girl", pron: "das mehdkhuhn" },
  { topic: "People and family", id: 9, noun: "die Familie", plural: "Familien", english: "family", pron: "dee familee" },
  { topic: "People and family", id: 10, noun: "die Eltern", plural: "—", english: "parents", pron: "dee uhltairn" },
  { topic: "People and family", id: 11, noun: "der Vater", plural: "Väter", english: "father", pron: "dair fatair" },
  { topic: "People and family", id: 12, noun: "die Mutter", plural: "Mütter", english: "mother", pron: "dee muttair" },
  { topic: "People and family", id: 13, noun: "der Papa", plural: "Papas", english: "dad", pron: "dair papa" },
  { topic: "People and family", id: 14, noun: "die Mama", plural: "Mamas", english: "mom", pron: "dee mama" },
  { topic: "People and family", id: 15, noun: "der Sohn", plural: "Söhne", english: "son", pron: "dair sohn" },
  { topic: "People and family", id: 16, noun: "die Tochter", plural: "Töchter", english: "daughter", pron: "dee tokhtair" },
  { topic: "People and family", id: 17, noun: "der Bruder", plural: "Brüder", english: "brother", pron: "dair brudair" },
  { topic: "People and family", id: 18, noun: "die Schwester", plural: "Schwestern", english: "sister", pron: "dee shfuhshtair" },
  { topic: "People and family", id: 19, noun: "der Großvater", plural: "Großväter", english: "grandfather", pron: "dair grossfatair" },
  { topic: "People and family", id: 20, noun: "die Großmutter", plural: "Großmütter", english: "grandmother", pron: "dee grossmuttair" },
  { topic: "People and family", id: 21, noun: "der Opa", plural: "Opas", english: "grandpa", pron: "dair opa" },
  { topic: "People and family", id: 22, noun: "die Oma", plural: "Omas", english: "grandma", pron: "dee oma" },
  { topic: "People and family", id: 23, noun: "der Onkel", plural: "Onkel", english: "uncle", pron: "dair onkuhl" },
  { topic: "People and family", id: 24, noun: "die Tante", plural: "Tanten", english: "aunt", pron: "dee tantuh" },
  { topic: "People and family", id: 25, noun: "der Cousin", plural: "Cousins", english: "male cousin", pron: "dair cousin" },
  { topic: "People and family", id: 26, noun: "die Cousine", plural: "Cousinen", english: "female cousin", pron: "dee cousinuh" },
  { topic: "People and family", id: 27, noun: "der Enkel", plural: "Enkel", english: "grandson", pron: "dair uhnkuhl" },
  { topic: "People and family", id: 28, noun: "die Enkelin", plural: "Enkelinnen", english: "granddaughter", pron: "dee uhnkuhlin" },
  { topic: "People and family", id: 29, noun: "der Freund", plural: "Freunde", english: "male friend / boyfriend", pron: "dair froynd" },
  { topic: "People and family", id: 30, noun: "die Freundin", plural: "Freundinnen", english: "female friend / girlfriend", pron: "dee froyndin" },
  { topic: "People and family", id: 31, noun: "der Nachbar", plural: "Nachbarn", english: "male neighbor", pron: "dair nakhbar" },
  { topic: "People and family", id: 32, noun: "die Nachbarin", plural: "Nachbarinnen", english: "female neighbor", pron: "dee nakhbarin" },
  { topic: "People and family", id: 33, noun: "der Gast", plural: "Gäste", english: "guest", pron: "dair gasht" },
  { topic: "People and family", id: 34, noun: "der Name", plural: "Namen", english: "name", pron: "dair namuh" },
  { topic: "People and family", id: 35, noun: "der Vorname", plural: "Vornamen", english: "first name", pron: "dair fornamuh" },
  { topic: "People and family", id: 36, noun: "der Familienname", plural: "Familiennamen", english: "family name", pron: "dair famileennamuh" },
  { topic: "People and family", id: 37, noun: "der Nachname", plural: "Nachnamen", english: "last name", pron: "dair nakhnamuh" },
  { topic: "People and family", id: 38, noun: "das Alter", plural: "—", english: "age", pron: "das altair" },
  { topic: "People and family", id: 39, noun: "der Geburtstag", plural: "Geburtstage", english: "birthday", pron: "dair guhburtshtag" },
  { topic: "People and family", id: 40, noun: "die Adresse", plural: "Adressen", english: "address", pron: "dee adruhssuh" },
  { topic: "People and family", id: 41, noun: "die Telefonnummer", plural: "Telefonnummern", english: "telephone number", pron: "dee tuhluhfonnummair" },

  // Topic: Home and rooms (42 - 78)
  { topic: "Home and rooms", id: 42, noun: "das Haus", plural: "Häuser", english: "house", pron: "das hows" },
  { topic: "Home and rooms", id: 43, noun: "die Wohnung", plural: "Wohnungen", english: "apartment", pron: "dee fohnung" },
  { topic: "Home and rooms", id: 44, noun: "das Zimmer", plural: "Zimmer", english: "room", pron: "das tsimmair" },
  { topic: "Home and rooms", id: 45, noun: "das Wohnzimmer", plural: "Wohnzimmer", english: "living room", pron: "das fohntsimmair" },
  { topic: "Home and rooms", id: 46, noun: "das Schlafzimmer", plural: "Schlafzimmer", english: "bedroom", pron: "das shlaftsimmair" },
  { topic: "Home and rooms", id: 47, noun: "das Kinderzimmer", plural: "Kinderzimmer", english: "children's room", pron: "das kindairtsimmair" },
  { topic: "Home and rooms", id: 48, noun: "das Badezimmer", plural: "Badezimmer", english: "bathroom", pron: "das baduhtsimmair" },
  { topic: "Home and rooms", id: 49, noun: "die Küche", plural: "Küchen", english: "kitchen", pron: "dee kuekhuh" },
  { topic: "Home and rooms", id: 50, noun: "der Flur", plural: "Flure", english: "hallway", pron: "dair flur" },
  { topic: "Home and rooms", id: 51, noun: "der Balkon", plural: "Balkone", english: "balcony", pron: "dair balkon" },
  { topic: "Home and rooms", id: 52, noun: "der Garten", plural: "Gärten", english: "garden", pron: "dair gartuhn" },
  { topic: "Home and rooms", id: 53, noun: "die Garage", plural: "Garagen", english: "garage", pron: "dee garaguh" },
  { topic: "Home and rooms", id: 54, noun: "der Keller", plural: "Keller", english: "cellar / basement", pron: "dair kuhllair" },
  { topic: "Home and rooms", id: 55, noun: "der Stock", plural: "Stockwerke", english: "floor / storey", pron: "dair shtock" },
  { topic: "Home and rooms", id: 56, noun: "das Erdgeschoss", plural: "Erdgeschosse", english: "ground floor", pron: "das airdguhshoss" },
  { topic: "Home and rooms", id: 57, noun: "die Etage", plural: "Etagen", english: "floor / storey", pron: "dee uhtaguh" },
  { topic: "Home and rooms", id: 58, noun: "die Treppe", plural: "Treppen", english: "stairs", pron: "dee truhppuh" },
  { topic: "Home and rooms", id: 59, noun: "der Aufzug", plural: "Aufzüge", english: "elevator", pron: "dair owftsug" },
  { topic: "Home and rooms", id: 60, noun: "die Tür", plural: "Türen", english: "door", pron: "dee tuer" },
  { topic: "Home and rooms", id: 61, noun: "das Fenster", plural: "Fenster", english: "window", pron: "das fuhnshtair" },
  { topic: "Home and rooms", id: 62, noun: "die Wand", plural: "Wände", english: "wall", pron: "dee fand" },
  { topic: "Home and rooms", id: 63, noun: "der Boden", plural: "Böden", english: "floor / ground", pron: "dair boduhn" },
  { topic: "Home and rooms", id: 64, noun: "die Decke", plural: "Decken", english: "ceiling / blanket", pron: "dee duhckuh" },
  { topic: "Home and rooms", id: 65, noun: "das Dach", plural: "Dächer", english: "roof", pron: "das dakh" },
  { topic: "Home and rooms", id: 66, noun: "der Schlüssel", plural: "Schlüssel", english: "key", pron: "dair shluessuhl" },
  { topic: "Home and rooms", id: 67, noun: "das Schloss", plural: "Schlösser", english: "lock / castle", pron: "das shloss" },
  { topic: "Home and rooms", id: 68, noun: "die Miete", plural: "Mieten", english: "rent", pron: "dee meetuh" },
  { topic: "Home and rooms", id: 69, noun: "der Vermieter", plural: "Vermieter", english: "landlord", pron: "dair fairmeetair" },
  { topic: "Home and rooms", id: 70, noun: "die Vermieterin", plural: "Vermieterinnen", english: "landlady", pron: "dee fairmeetairin" },
  { topic: "Home and rooms", id: 71, noun: "der Mieter", plural: "Mieter", english: "tenant", pron: "dair meetair" },
  { topic: "Home and rooms", id: 72, noun: "die Mieterin", plural: "Mieterinnen", english: "female tenant", pron: "dee meetairin" },
  { topic: "Home and rooms", id: 73, noun: "die Nebenkosten", plural: "—", english: "additional housing costs", pron: "dee nuhbuhnkoshtuhn" },
  { topic: "Home and rooms", id: 74, noun: "der Strom", plural: "—", english: "electricity", pron: "dair shtrom" },
  { topic: "Home and rooms", id: 75, noun: "das Gas", plural: "—", english: "gas", pron: "das gas" },
  { topic: "Home and rooms", id: 76, noun: "das Wasser", plural: "—", english: "water", pron: "das fassair" },
  { topic: "Home and rooms", id: 77, noun: "die Heizung", plural: "Heizungen", english: "heating", pron: "dee heyetsung" },
  { topic: "Home and rooms", id: 78, noun: "die Mülltonne", plural: "Mülltonnen", english: "trash bin", pron: "dee muelltonnuh" },

  // Topic: Furniture and household objects (79 - 129)
  { topic: "Furniture and household objects", id: 79, noun: "der Tisch", plural: "Tische", english: "table", pron: "dair tish" },
  { topic: "Furniture and household objects", id: 80, noun: "der Stuhl", plural: "Stühle", english: "chair", pron: "dair shtuhl" },
  { topic: "Furniture and household objects", id: 81, noun: "das Sofa", plural: "Sofas", english: "sofa", pron: "das sofa" },
  { topic: "Furniture and household objects", id: 82, noun: "der Sessel", plural: "Sessel", english: "armchair", pron: "dair suhssuhl" },
  { topic: "Furniture and household objects", id: 83, noun: "das Bett", plural: "Betten", english: "bed", pron: "das buhtt" },
  { topic: "Furniture and household objects", id: 84, noun: "der Schrank", plural: "Schränke", english: "cupboard / wardrobe", pron: "dair shrank" },
  { topic: "Furniture and household objects", id: 85, noun: "das Regal", plural: "Regale", english: "shelf", pron: "das ruhgal" },
  { topic: "Furniture and household objects", id: 86, noun: "die Kommode", plural: "Kommoden", english: "chest of drawers", pron: "dee kommoduh" },
  { topic: "Furniture and household objects", id: 87, noun: "die Lampe", plural: "Lampen", english: "lamp", pron: "dee lampuh" },
  { topic: "Furniture and household objects", id: 88, noun: "das Licht", plural: "Lichter", english: "light", pron: "das likht" },
  { topic: "Furniture and household objects", id: 89, noun: "der Teppich", plural: "Teppiche", english: "carpet", pron: "dair tuhppikh" },
  { topic: "Furniture and household objects", id: 90, noun: "der Spiegel", plural: "Spiegel", english: "mirror", pron: "dair shpeeguhl" },
  { topic: "Furniture and household objects", id: 91, noun: "das Bild", plural: "Bilder", english: "picture", pron: "das bild" },
  { topic: "Furniture and household objects", id: 92, noun: "die Uhr", plural: "Uhren", english: "clock / watch", pron: "dee uhr" },
  { topic: "Furniture and household objects", id: 93, noun: "der Fernseher", plural: "Fernseher", english: "television", pron: "dair fairnsuhhair" },
  { topic: "Furniture and household objects", id: 94, noun: "das Radio", plural: "Radios", english: "radio", pron: "das radio" },
  { topic: "Furniture and household objects", id: 95, noun: "der Computer", plural: "Computer", english: "computer", pron: "dair computair" },
  { topic: "Furniture and household objects", id: 96, noun: "der Laptop", plural: "Laptops", english: "laptop", pron: "dair laptop" },
  { topic: "Furniture and household objects", id: 97, noun: "das Telefon", plural: "Telefone", english: "telephone", pron: "das tuhluhfon" },
  { topic: "Furniture and household objects", id: 98, noun: "das Handy", plural: "Handys", english: "mobile phone", pron: "das handy" },
  { topic: "Furniture and household objects", id: 99, noun: "der Kühlschrank", plural: "Kühlschränke", english: "refrigerator", pron: "dair kuehlshrank" },
  { topic: "Furniture and household objects", id: 100, noun: "der Herd", plural: "Herde", english: "stove", pron: "dair haird" },
  { topic: "Furniture and household objects", id: 101, noun: "der Ofen", plural: "Öfen", english: "oven", pron: "dair ofuhn" },
  { topic: "Furniture and household objects", id: 102, noun: "die Mikrowelle", plural: "Mikrowellen", english: "microwave", pron: "dee mikrofuhlluh" },
  { topic: "Furniture and household objects", id: 103, noun: "die Spülmaschine", plural: "Spülmaschinen", english: "dishwasher", pron: "dee shpuelmashinuh" },
  { topic: "Furniture and household objects", id: 104, noun: "die Waschmaschine", plural: "Waschmaschinen", english: "washing machine", pron: "dee fashmashinuh" },
  { topic: "Furniture and household objects", id: 105, noun: "der Staubsauger", plural: "Staubsauger", english: "vacuum cleaner", pron: "dair shtowbsowgair" },
  { topic: "Furniture and household objects", id: 106, noun: "die Dusche", plural: "Duschen", english: "shower", pron: "dee dushuh" },
  { topic: "Furniture and household objects", id: 107, noun: "die Badewanne", plural: "Badewannen", english: "bathtub", pron: "dee baduhfannuh" },
  { topic: "Furniture and household objects", id: 108, noun: "die Toilette", plural: "Toiletten", english: "toilet", pron: "dee toiluhttuh" },
  { topic: "Furniture and household objects", id: 109, noun: "das Handtuch", plural: "Handtücher", english: "towel", pron: "das handtukh" },
  { topic: "Furniture and household objects", id: 110, noun: "die Seife", plural: "Seifen", english: "soap", pron: "dee seyefuh" },
  { topic: "Furniture and household objects", id: 111, noun: "die Zahnbürste", plural: "Zahnbürsten", english: "toothbrush", pron: "dee tsahnbuershtuh" },
  { topic: "Furniture and household objects", id: 112, noun: "die Zahnpasta", plural: "—", english: "toothpaste", pron: "dee tsahnpashta" },
  { topic: "Furniture and household objects", id: 113, noun: "der Kamm", plural: "Kämme", english: "comb", pron: "dair kamm" },
  { topic: "Furniture and household objects", id: 114, noun: "die Bürste", plural: "Bürsten", english: "brush", pron: "dee buershtuh" },
  { topic: "Furniture and household objects", id: 115, noun: "das Glas", plural: "Gläser", english: "glass", pron: "das glas" },
  { topic: "Furniture and household objects", id: 116, noun: "die Tasse", plural: "Tassen", english: "cup", pron: "dee tassuh" },
  { topic: "Furniture and household objects", id: 117, noun: "der Becher", plural: "Becher", english: "mug / cup", pron: "dair buhkhair" },
  { topic: "Furniture and household objects", id: 118, noun: "der Teller", plural: "Teller", english: "plate", pron: "dair tuhllair" },
  { topic: "Furniture and household objects", id: 119, noun: "die Schüssel", plural: "Schüsseln", english: "bowl", pron: "dee shuessuhl" },
  { topic: "Furniture and household objects", id: 120, noun: "das Messer", plural: "Messer", english: "knife", pron: "das muhssair" },
  { topic: "Furniture and household objects", id: 121, noun: "die Gabel", plural: "Gabeln", english: "fork", pron: "dee gabuhl" },
  { topic: "Furniture and household objects", id: 122, noun: "der Löffel", plural: "Löffel", english: "spoon", pron: "dair lurffuhl" },
  { topic: "Furniture and household objects", id: 123, noun: "der Topf", plural: "Töpfe", english: "pot", pron: "dair topf" },
  { topic: "Furniture and household objects", id: 124, noun: "die Pfanne", plural: "Pfannen", english: "pan", pron: "dee pfannuh" },
  { topic: "Furniture and household objects", id: 125, noun: "die Flasche", plural: "Flaschen", english: "bottle", pron: "dee flashuh" },
  { topic: "Furniture and household objects", id: 126, noun: "die Dose", plural: "Dosen", english: "can / tin", pron: "dee dosuh" },
  { topic: "Furniture and household objects", id: 127, noun: "die Packung", plural: "Packungen", english: "packet / package", pron: "dee packung" },
  { topic: "Furniture and household objects", id: 128, noun: "die Tüte", plural: "Tüten", english: "bag", pron: "dee tuetuh" },
  { topic: "Furniture and household objects", id: 129, noun: "der Müll", plural: "—", english: "rubbish", pron: "dair muell" },

  // Topic: Food and drink (130 - 196)
  { topic: "Food and drink", id: 130, noun: "das Essen", plural: "—", english: "food / meal", pron: "das uhssuhn" },
  { topic: "Food and drink", id: 131, noun: "das Getränk", plural: "Getränke", english: "drink / beverage", pron: "das guhtrehnk" },
  { topic: "Food and drink", id: 132, noun: "das Frühstück", plural: "Frühstücke", english: "breakfast", pron: "das fruehshtueck" },
  { topic: "Food and drink", id: 133, noun: "das Mittagessen", plural: "—", english: "lunch", pron: "das mittaguhssuhn" },
  { topic: "Food and drink", id: 134, noun: "das Abendessen", plural: "—", english: "dinner", pron: "das abuhnduhssuhn" },
  { topic: "Food and drink", id: 135, noun: "das Brot", plural: "Brote", english: "bread", pron: "das brot" },
  { topic: "Food and drink", id: 136, noun: "das Brötchen", plural: "Brötchen", english: "bread roll", pron: "das brurtkhuhn" },
  { topic: "Food and drink", id: 137, noun: "der Toast", plural: "Toasts", english: "toast", pron: "dair toasht" },
  { topic: "Food and drink", id: 138, noun: "der Kuchen", plural: "Kuchen", english: "cake", pron: "dair kukhuhn" },
  { topic: "Food and drink", id: 139, noun: "der Keks", plural: "Kekse", english: "cookie", pron: "dair kuhks" },
  { topic: "Food and drink", id: 140, noun: "die Torte", plural: "Torten", english: "cream cake", pron: "dee tortuh" },
  { topic: "Food and drink", id: 141, noun: "das Mehl", plural: "—", english: "flour", pron: "das muhhl" },
  { topic: "Food and drink", id: 142, noun: "der Zucker", plural: "—", english: "sugar", pron: "dair tsuckair" },
  { topic: "Food and drink", id: 143, noun: "das Salz", plural: "—", english: "salt", pron: "das salts" },
  { topic: "Food and drink", id: 144, noun: "der Pfeffer", plural: "—", english: "pepper", pron: "dair pfuhffair" },
  { topic: "Food and drink", id: 145, noun: "die Butter", plural: "—", english: "butter", pron: "dee buttair" },
  { topic: "Food and drink", id: 146, noun: "der Käse", plural: "—", english: "cheese", pron: "dair kehsuh" },
  { topic: "Food and drink", id: 147, noun: "die Milch", plural: "—", english: "milk", pron: "dee milkh" },
  { topic: "Food and drink", id: 148, noun: "der Joghurt", plural: "Joghurts", english: "yogurt", pron: "dair yoghurt" },
  { topic: "Food and drink", id: 149, noun: "das Ei", plural: "Eier", english: "egg", pron: "das eye" },
  { topic: "Food and drink", id: 150, noun: "das Fleisch", plural: "—", english: "meat", pron: "das fleyesh" },
  { topic: "Food and drink", id: 151, noun: "das Hähnchen", plural: "Hähnchen", english: "chicken", pron: "das hehhnkhuhn" },
  { topic: "Food and drink", id: 152, noun: "das Huhn", plural: "Hühner", english: "chicken / hen", pron: "das huhn" },
  { topic: "Food and drink", id: 153, noun: "der Fisch", plural: "Fische", english: "fish", pron: "dair fish" },
  { topic: "Food and drink", id: 154, noun: "die Wurst", plural: "Würste", english: "sausage", pron: "dee fursht" },
  { topic: "Food and drink", id: 155, noun: "der Schinken", plural: "—", english: "ham", pron: "dair shinkuhn" },
  { topic: "Food and drink", id: 156, noun: "der Reis", plural: "—", english: "rice", pron: "dair reyes" },
  { topic: "Food and drink", id: 157, noun: "die Nudel", plural: "Nudeln", english: "noodle / pasta", pron: "dee nuduhl" },
  { topic: "Food and drink", id: 158, noun: "die Suppe", plural: "Suppen", english: "soup", pron: "dee suppuh" },
  { topic: "Food and drink", id: 159, noun: "der Salat", plural: "Salate", english: "salad", pron: "dair salat" },
  { topic: "Food and drink", id: 160, noun: "das Gemüse", plural: "—", english: "vegetables", pron: "das guhmuesuh" },
  { topic: "Food and drink", id: 161, noun: "die Kartoffel", plural: "Kartoffeln", english: "potato", pron: "dee kartoffuhl" },
  { topic: "Food and drink", id: 162, noun: "die Tomate", plural: "Tomaten", english: "tomato", pron: "dee tomatuh" },
  { topic: "Food and drink", id: 163, noun: "die Gurke", plural: "Gurken", english: "cucumber", pron: "dee gurkuh" },
  { topic: "Food and drink", id: 164, noun: "die Zwiebel", plural: "Zwiebeln", english: "onion", pron: "dee tsfeebuhl" },
  { topic: "Food and drink", id: 165, noun: "die Karotte", plural: "Karotten", english: "carrot", pron: "dee karottuh" },
  { topic: "Food and drink", id: 166, noun: "die Möhre", plural: "Möhren", english: "carrot", pron: "dee murhruh" },
  { topic: "Food and drink", id: 167, noun: "der Pilz", plural: "Pilze", english: "mushroom", pron: "dair pilts" },
  { topic: "Food and drink", id: 168, noun: "die Bohne", plural: "Bohnen", english: "bean", pron: "dee bohnuh" },
  { topic: "Food and drink", id: 169, noun: "die Erbse", plural: "Erbsen", english: "pea", pron: "dee airbsuh" },
  { topic: "Food and drink", id: 170, noun: "der Mais", plural: "—", english: "corn", pron: "dair mais" },
  { topic: "Food and drink", id: 171, noun: "das Obst", plural: "—", english: "fruit", pron: "das obsht" },
  { topic: "Food and drink", id: 172, noun: "der Apfel", plural: "Äpfel", english: "apple", pron: "dair apfuhl" },
  { topic: "Food and drink", id: 173, noun: "die Banane", plural: "Bananen", english: "banana", pron: "dee bananuh" },
  { topic: "Food and drink", id: 174, noun: "die Orange", plural: "Orangen", english: "orange", pron: "dee oranguh" },
  { topic: "Food and drink", id: 175, noun: "die Zitrone", plural: "Zitronen", english: "lemon", pron: "dee tsitronuh" },
  { topic: "Food and drink", id: 176, noun: "die Birne", plural: "Birnen", english: "pear", pron: "dee birnuh" },
  { topic: "Food and drink", id: 177, noun: "die Erdbeere", plural: "Erdbeeren", english: "strawberry", pron: "dee airdbuhairuh" },
  { topic: "Food and drink", id: 178, noun: "die Traube", plural: "Trauben", english: "grape", pron: "dee trowbuh" },
  { topic: "Food and drink", id: 179, noun: "die Kirsche", plural: "Kirschen", english: "cherry", pron: "dee kirshuh" },
  { topic: "Food and drink", id: 180, noun: "die Melone", plural: "Melonen", english: "melon", pron: "dee muhlonuh" },
  { topic: "Food and drink", id: 181, noun: "das Öl", plural: "Öle", english: "oil", pron: "das url" },
  { topic: "Food and drink", id: 182, noun: "die Marmelade", plural: "Marmeladen", english: "jam", pron: "dee marmuhladuh" },
  { topic: "Food and drink", id: 183, noun: "der Honig", plural: "—", english: "honey", pron: "dair honig" },
  { topic: "Food and drink", id: 184, noun: "die Schokolade", plural: "Schokoladen", english: "chocolate", pron: "dee shokoladuh" },
  { topic: "Food and drink", id: 185, noun: "das Eis", plural: "—", english: "ice cream / ice", pron: "das eyes" },
  { topic: "Food and drink", id: 186, noun: "die Pizza", plural: "Pizzen", english: "pizza", pron: "dee pitstsa" },
  { topic: "Food and drink", id: 187, noun: "der Hamburger", plural: "Hamburger", english: "hamburger", pron: "dair hamburgair" },
  { topic: "Food and drink", id: 188, noun: "das Sandwich", plural: "Sandwiches", english: "sandwich", pron: "das sandfikh" },
  { topic: "Food and drink", id: 189, noun: "der Kaffee", plural: "Kaffees", english: "coffee", pron: "dair kaffuhuh" },
  { topic: "Food and drink", id: 190, noun: "der Tee", plural: "Tees", english: "tea", pron: "dair tuhuh" },
  { topic: "Food and drink", id: 191, noun: "der Saft", plural: "Säfte", english: "juice", pron: "dair saft" },
  { topic: "Food and drink", id: 192, noun: "das Mineralwasser", plural: "—", english: "mineral water", pron: "das minairalfassair" },
  { topic: "Food and drink", id: 193, noun: "das Bier", plural: "Biere", english: "beer", pron: "das beer" },
  { topic: "Food and drink", id: 194, noun: "der Wein", plural: "Weine", english: "wine", pron: "dair feyen" },
  { topic: "Food and drink", id: 195, noun: "der Hunger", plural: "—", english: "hunger", pron: "dair hungair" },
  { topic: "Food and drink", id: 196, noun: "der Durst", plural: "—", english: "thirst", pron: "dair dursht" },

  // Topic: Clothing and personal items (197 - 223)
  { topic: "Clothing and personal items", id: 197, noun: "die Kleidung", plural: "—", english: "clothing", pron: "dee kleyedung" },
  { topic: "Clothing and personal items", id: 198, noun: "die Hose", plural: "Hosen", english: "trousers", pron: "dee hosuh" },
  { topic: "Clothing and personal items", id: 199, noun: "die Jeans", plural: "—", english: "jeans", pron: "dee yuhans" },
  { topic: "Clothing and personal items", id: 200, noun: "das Kleid", plural: "Kleider", english: "dress", pron: "das kleyed" },
  { topic: "Clothing and personal items", id: 201, noun: "der Rock", plural: "Röcke", english: "skirt", pron: "dair rock" },
  { topic: "Clothing and personal items", id: 202, noun: "das Hemd", plural: "Hemden", english: "shirt", pron: "das huhmd" },
  { topic: "Clothing and personal items", id: 203, noun: "die Bluse", plural: "Blusen", english: "blouse", pron: "dee blusuh" },
  { topic: "Clothing and personal items", id: 204, noun: "das T-Shirt", plural: "T-Shirts", english: "T-shirt", pron: "das t-shirt" },
  { topic: "Clothing and personal items", id: 205, noun: "der Pullover", plural: "Pullover", english: "sweater", pron: "dair pullofair" },
  { topic: "Clothing and personal items", id: 206, noun: "die Jacke", plural: "Jacken", english: "jacket", pron: "dee yackuh" },
  { topic: "Clothing and personal items", id: 207, noun: "der Mantel", plural: "Mäntel", english: "coat", pron: "dair mantuhl" },
  { topic: "Clothing and personal items", id: 208, noun: "der Anzug", plural: "Anzüge", english: "suit", pron: "dair antsug" },
  { topic: "Clothing and personal items", id: 209, noun: "die Socke", plural: "Socken", english: "sock", pron: "dee sockuh" },
  { topic: "Clothing and personal items", id: 210, noun: "der Schuh", plural: "Schuhe", english: "shoe", pron: "dair shuh" },
  { topic: "Clothing and personal items", id: 211, noun: "der Stiefel", plural: "Stiefel", english: "boot", pron: "dair shteefuhl" },
  { topic: "Clothing and personal items", id: 212, noun: "der Hut", plural: "Hüte", english: "hat", pron: "dair hut" },
  { topic: "Clothing and personal items", id: 213, noun: "die Mütze", plural: "Mützen", english: "cap / beanie", pron: "dee muettsuh" },
  { topic: "Clothing and personal items", id: 214, noun: "der Schal", plural: "Schals", english: "scarf", pron: "dair shal" },
  { topic: "Clothing and personal items", id: 215, noun: "der Gürtel", plural: "Gürtel", english: "belt", pron: "dair guertuhl" },
  { topic: "Clothing and personal items", id: 216, noun: "die Brille", plural: "Brillen", english: "glasses", pron: "dee brilluh" },
  { topic: "Clothing and personal items", id: 217, noun: "die Sonnenbrille", plural: "Sonnenbrillen", english: "sunglasses", pron: "dee sonnuhnbrilluh" },
  { topic: "Clothing and personal items", id: 218, noun: "die Tasche", plural: "Taschen", english: "bag", pron: "dee tashuh" },
  { topic: "Clothing and personal items", id: 219, noun: "der Koffer", plural: "Koffer", english: "suitcase", pron: "dair koffair" },
  { topic: "Clothing and personal items", id: 220, noun: "der Rucksack", plural: "Rucksäcke", english: "backpack", pron: "dair rucksack" },
  { topic: "Clothing and personal items", id: 221, noun: "der Regenschirm", plural: "Regenschirme", english: "umbrella", pron: "dair ruhguhnshirm" },
  { topic: "Clothing and personal items", id: 222, noun: "die Größe", plural: "Größen", english: "size", pron: "dee grurssuh" },
  { topic: "Clothing and personal items", id: 223, noun: "die Farbe", plural: "Farben", english: "color", pron: "dee farbuh" },

  // Topic: Body and health (224 - 264)
  { topic: "Body and health", id: 224, noun: "der Körper", plural: "Körper", english: "body", pron: "dair kurrpair" },
  { topic: "Body and health", id: 225, noun: "der Kopf", plural: "Köpfe", english: "head", pron: "dair kopf" },
  { topic: "Body and health", id: 226, noun: "das Gesicht", plural: "Gesichter", english: "face", pron: "das guhsikht" },
  { topic: "Body and health", id: 227, noun: "das Haar", plural: "Haare", english: "hair", pron: "das haar" },
  { topic: "Body and health", id: 228, noun: "das Auge", plural: "Augen", english: "eye", pron: "das owguh" },
  { topic: "Body and health", id: 229, noun: "das Ohr", plural: "Ohren", english: "ear", pron: "das ohr" },
  { topic: "Body and health", id: 230, noun: "die Nase", plural: "Nasen", english: "nose", pron: "dee nasuh" },
  { topic: "Body and health", id: 231, noun: "der Mund", plural: "Münder", english: "mouth", pron: "dair mund" },
  { topic: "Body and health", id: 232, noun: "der Zahn", plural: "Zähne", english: "tooth", pron: "dair tsahn" },
  { topic: "Body and health", id: 233, noun: "der Hals", plural: "Hälse", english: "neck / throat", pron: "dair hals" },
  { topic: "Body and health", id: 234, noun: "die Schulter", plural: "Schultern", english: "shoulder", pron: "dee shultair" },
  { topic: "Body and health", id: 235, noun: "der Arm", plural: "Arme", english: "arm", pron: "dair arm" },
  { topic: "Body and health", id: 236, noun: "die Hand", plural: "Hände", english: "hand", pron: "dee hand" },
  { topic: "Body and health", id: 237, noun: "der Finger", plural: "Finger", english: "finger", pron: "dair fingair" },
  { topic: "Body and health", id: 238, noun: "der Bauch", plural: "Bäuche", english: "stomach / belly", pron: "dair bowkh" },
  { topic: "Body and health", id: 239, noun: "der Rücken", plural: "Rücken", english: "back", pron: "dair rueckuhn" },
  { topic: "Body and health", id: 240, noun: "das Bein", plural: "Beine", english: "leg", pron: "das beyen" },
  { topic: "Body and health", id: 241, noun: "das Knie", plural: "Knie", english: "knee", pron: "das knee" },
  { topic: "Body and health", id: 242, noun: "der Fuß", plural: "Füße", english: "foot", pron: "dair fuss" },
  { topic: "Body and health", id: 243, noun: "das Herz", plural: "Herzen", english: "heart", pron: "das hairts" },
  { topic: "Body and health", id: 244, noun: "die Gesundheit", plural: "—", english: "health", pron: "dee guhsundheyet" },
  { topic: "Body and health", id: 245, noun: "die Krankheit", plural: "Krankheiten", english: "illness", pron: "dee krankheyet" },
  { topic: "Body and health", id: 246, noun: "der Schmerz", plural: "Schmerzen", english: "pain", pron: "dair shmairts" },
  { topic: "Body and health", id: 247, noun: "der Kopfschmerz", plural: "Kopfschmerzen", english: "headache", pron: "dair kopfshmairts" },
  { topic: "Body and health", id: 248, noun: "der Bauchschmerz", plural: "Bauchschmerzen", english: "stomachache", pron: "dair bowkhshmairts" },
  { topic: "Body and health", id: 249, noun: "die Erkältung", plural: "Erkältungen", english: "cold", pron: "dee airkehltung" },
  { topic: "Body and health", id: 250, noun: "der Husten", plural: "—", english: "cough", pron: "dair hushtuhn" },
  { topic: "Body and health", id: 251, noun: "der Schnupfen", plural: "—", english: "runny nose / cold", pron: "dair shnupfuhn" },
  { topic: "Body and health", id: 252, noun: "das Fieber", plural: "—", english: "fever", pron: "das feebair" },
  { topic: "Body and health", id: 253, noun: "der Arzt", plural: "Ärzte", english: "doctor", pron: "dair artst" },
  { topic: "Body and health", id: 254, noun: "die Ärztin", plural: "Ärztinnen", english: "female doctor", pron: "dee ehrtstin" },
  { topic: "Body and health", id: 255, noun: "der Zahnarzt", plural: "Zahnärzte", english: "dentist", pron: "dair tsahnartst" },
  { topic: "Body and health", id: 256, noun: "die Zahnärztin", plural: "Zahnärztinnen", english: "female dentist", pron: "dee tsahnehrtstin" },
  { topic: "Body and health", id: 257, noun: "das Krankenhaus", plural: "Krankenhäuser", english: "hospital", pron: "das krankuhnhows" },
  { topic: "Body and health", id: 258, noun: "die Praxis", plural: "Praxen", english: "doctor's office", pron: "dee praxis" },
  { topic: "Body and health", id: 259, noun: "die Apotheke", plural: "Apotheken", english: "pharmacy", pron: "dee apothuhkuh" },
  { topic: "Body and health", id: 260, noun: "die Medizin", plural: "—", english: "medicine", pron: "dee muhditsin" },
  { topic: "Body and health", id: 261, noun: "das Medikament", plural: "Medikamente", english: "medication", pron: "das muhdikamuhnt" },
  { topic: "Body and health", id: 262, noun: "die Tablette", plural: "Tabletten", english: "tablet / pill", pron: "dee tabluhttuh" },
  { topic: "Body and health", id: 263, noun: "das Rezept", plural: "Rezepte", english: "prescription / recipe", pron: "das ruhtsuhpt" },
  { topic: "Body and health", id: 264, noun: "der Termin", plural: "Termine", english: "appointment", pron: "dair tairmin" },

  // Topic: School and learning (265 - 302)
  { topic: "School and learning", id: 265, noun: "die Schule", plural: "Schulen", english: "school", pron: "dee shuluh" },
  { topic: "School and learning", id: 266, noun: "der Kindergarten", plural: "Kindergärten", english: "kindergarten", pron: "dair kindairgartuhn" },
  { topic: "School and learning", id: 267, noun: "die Universität", plural: "Universitäten", english: "university", pron: "dee unifairsiteht" },
  { topic: "School and learning", id: 268, noun: "der Kurs", plural: "Kurse", english: "course", pron: "dair kurs" },
  { topic: "School and learning", id: 269, noun: "die Klasse", plural: "Klassen", english: "class", pron: "dee klassuh" },
  { topic: "School and learning", id: 270, noun: "der Unterricht", plural: "—", english: "lesson / instruction", pron: "dair untairrikht" },
  { topic: "School and learning", id: 271, noun: "die Pause", plural: "Pausen", english: "break", pron: "dee powsuh" },
  { topic: "School and learning", id: 272, noun: "der Lehrer", plural: "Lehrer", english: "male teacher", pron: "dair luhhrair" },
  { topic: "School and learning", id: 273, noun: "die Lehrerin", plural: "Lehrerinnen", english: "female teacher", pron: "dee luhhrairin" },
  { topic: "School and learning", id: 274, noun: "der Schüler", plural: "Schüler", english: "male pupil", pron: "dair shuelair" },
  { topic: "School and learning", id: 275, noun: "die Schülerin", plural: "Schülerinnen", english: "female pupil", pron: "dee shuelairin" },
  { topic: "School and learning", id: 276, noun: "der Student", plural: "Studenten", english: "male student", pron: "dair shtuduhnt" },
  { topic: "School and learning", id: 277, noun: "die Studentin", plural: "Studentinnen", english: "female student", pron: "dee shtuduhntin" },
  { topic: "School and learning", id: 278, noun: "das Buch", plural: "Bücher", english: "book", pron: "das bukh" },
  { topic: "School and learning", id: 279, noun: "das Wörterbuch", plural: "Wörterbücher", english: "dictionary", pron: "das furrtairbukh" },
  { topic: "School and learning", id: 280, noun: "das Heft", plural: "Hefte", english: "exercise book", pron: "das huhft" },
  { topic: "School and learning", id: 281, noun: "das Papier", plural: "Papiere", english: "paper", pron: "das papeer" },
  { topic: "School and learning", id: 282, noun: "der Stift", plural: "Stifte", english: "pen", pron: "dair shtift" },
  { topic: "School and learning", id: 283, noun: "der Kugelschreiber", plural: "Kugelschreiber", english: "ballpoint pen", pron: "dair kuguhlshreyebair" },
  { topic: "School and learning", id: 284, noun: "der Bleistift", plural: "Bleistifte", english: "pencil", pron: "dair bleyeshtift" },
  { topic: "School and learning", id: 285, noun: "der Radiergummi", plural: "Radiergummis", english: "eraser", pron: "dair radeergummi" },
  { topic: "School and learning", id: 286, noun: "die Tafel", plural: "Tafeln", english: "board", pron: "dee tafuhl" },
  { topic: "School and learning", id: 287, noun: "die Aufgabe", plural: "Aufgaben", english: "task / exercise", pron: "dee owfgabuh" },
  { topic: "School and learning", id: 288, noun: "die Hausaufgabe", plural: "Hausaufgaben", english: "homework", pron: "dee howsowfgabuh" },
  { topic: "School and learning", id: 289, noun: "die Übung", plural: "Übungen", english: "exercise", pron: "dee uebung" },
  { topic: "School and learning", id: 290, noun: "die Prüfung", plural: "Prüfungen", english: "exam", pron: "dee pruefung" },
  { topic: "School and learning", id: 291, noun: "die Frage", plural: "Fragen", english: "question", pron: "dee fraguh" },
  { topic: "School and learning", id: 292, noun: "die Antwort", plural: "Antworten", english: "answer", pron: "dee antfort" },
  { topic: "School and learning", id: 293, noun: "das Beispiel", plural: "Beispiele", english: "example", pron: "das beyeshpeel" },
  { topic: "School and learning", id: 294, noun: "das Wort", plural: "Wörter", english: "word", pron: "das fort" },
  { topic: "School and learning", id: 295, noun: "der Satz", plural: "Sätze", english: "sentence", pron: "dair satts" },
  { topic: "School and learning", id: 296, noun: "der Text", plural: "Texte", english: "text", pron: "dair tuhxt" },
  { topic: "School and learning", id: 297, noun: "die Sprache", plural: "Sprachen", english: "language", pron: "dee shprakhuh" },
  { topic: "School and learning", id: 298, noun: "das Deutsch", plural: "—", english: "German language", pron: "das doych" },
  { topic: "School and learning", id: 299, noun: "der Buchstabe", plural: "Buchstaben", english: "letter of alphabet", pron: "dair bukhshtabuh" },
  { topic: "School and learning", id: 300, noun: "die Zahl", plural: "Zahlen", english: "number", pron: "dee tsahl" },
  { topic: "School and learning", id: 301, noun: "die Note", plural: "Noten", english: "grade / note", pron: "dee notuh" },
  { topic: "School and learning", id: 302, noun: "der Fehler", plural: "Fehler", english: "mistake", pron: "dair fuhhlair" },

  // Topic: Work and occupations (303 - 337)
  { topic: "Work and occupations", id: 303, noun: "die Arbeit", plural: "Arbeiten", english: "work / job", pron: "dee arbeyet" },
  { topic: "Work and occupations", id: 304, noun: "der Beruf", plural: "Berufe", english: "profession", pron: "dair bairuf" },
  { topic: "Work and occupations", id: 305, noun: "die Firma", plural: "Firmen", english: "company", pron: "dee firma" },
  { topic: "Work and occupations", id: 306, noun: "das Büro", plural: "Büros", english: "office", pron: "das buero" },
  { topic: "Work and occupations", id: 307, noun: "der Arbeitsplatz", plural: "Arbeitsplätze", english: "workplace", pron: "dair arbeyetshplatts" },
  { topic: "Work and occupations", id: 308, noun: "der Chef", plural: "Chefs", english: "male boss", pron: "dair khuhf" },
  { topic: "Work and occupations", id: 309, noun: "die Chefin", plural: "Chefinnen", english: "female boss", pron: "dee khuhfin" },
  { topic: "Work and occupations", id: 310, noun: "der Kollege", plural: "Kollegen", english: "male colleague", pron: "dair kolluhguh" },
  { topic: "Work and occupations", id: 311, noun: "die Kollegin", plural: "Kolleginnen", english: "female colleague", pron: "dee kolluhgin" },
  { topic: "Work and occupations", id: 312, noun: "der Mitarbeiter", plural: "Mitarbeiter", english: "male employee", pron: "dair mitarbeyetair" },
  { topic: "Work and occupations", id: 313, noun: "die Mitarbeiterin", plural: "Mitarbeiterinnen", english: "female employee", pron: "dee mitarbeyetairin" },
  { topic: "Work and occupations", id: 314, noun: "der Kunde", plural: "Kunden", english: "male customer", pron: "dair kunduh" },
  { topic: "Work and occupations", id: 315, noun: "die Kundin", plural: "Kundinnen", english: "female customer", pron: "dee kundin" },
  { topic: "Work and occupations", id: 316, noun: "der Verkäufer", plural: "Verkäufer", english: "salesman", pron: "dair fairkoyfair" },
  { topic: "Work and occupations", id: 317, noun: "die Verkäuferin", plural: "Verkäuferinnen", english: "saleswoman", pron: "dee fairkoyfairin" },
  { topic: "Work and occupations", id: 318, noun: "der Kellner", plural: "Kellner", english: "waiter", pron: "dair kuhllnair" },
  { topic: "Work and occupations", id: 319, noun: "die Kellnerin", plural: "Kellnerinnen", english: "waitress", pron: "dee kuhllnairin" },
  { topic: "Work and occupations", id: 320, noun: "der Koch", plural: "Köche", english: "cook / chef", pron: "dair kokh" },
  { topic: "Work and occupations", id: 321, noun: "die Köchin", plural: "Köchinnen", english: "female cook", pron: "dee kurkhin" },
  { topic: "Work and occupations", id: 322, noun: "der Fahrer", plural: "Fahrer", english: "driver", pron: "dair fahrair" },
  { topic: "Work and occupations", id: 323, noun: "die Fahrerin", plural: "Fahrerinnen", english: "female driver", pron: "dee fahrairin" },
  { topic: "Work and occupations", id: 324, noun: "der Polizist", plural: "Polizisten", english: "policeman", pron: "dair politsisht" },
  { topic: "Work and occupations", id: 325, noun: "die Polizistin", plural: "Polizistinnen", english: "policewoman", pron: "dee politsishtin" },
  { topic: "Work and occupations", id: 326, noun: "der Mechaniker", plural: "Mechaniker", english: "mechanic", pron: "dair muhkhanikair" },
  { topic: "Work and occupations", id: 327, noun: "die Sekretärin", plural: "Sekretärinnen", english: "secretary", pron: "dee suhkruhtehrin" },
  { topic: "Work and occupations", id: 328, noun: "der Friseur", plural: "Friseure", english: "hairdresser", pron: "dair frisoyr" },
  { topic: "Work and occupations", id: 329, noun: "die Friseurin", plural: "Friseurinnen", english: "female hairdresser", pron: "dee frisoyrin" },
  { topic: "Work and occupations", id: 330, noun: "der Ingenieur", plural: "Ingenieure", english: "engineer", pron: "dair inguhneeur" },
  { topic: "Work and occupations", id: 331, noun: "die Ingenieurin", plural: "Ingenieurinnen", english: "female engineer", pron: "dee inguhneeurin" },
  { topic: "Work and occupations", id: 332, noun: "der Vertrag", plural: "Verträge", english: "contract", pron: "dair fairtrag" },
  { topic: "Work and occupations", id: 333, noun: "die Stelle", plural: "Stellen", english: "position / job", pron: "dee shtuhlluh" },
  { topic: "Work and occupations", id: 334, noun: "die Bewerbung", plural: "Bewerbungen", english: "application", pron: "dee buhfairbung" },
  { topic: "Work and occupations", id: 335, noun: "der Lebenslauf", plural: "Lebensläufe", english: "CV / résumé", pron: "dair luhbuhnslowf" },
  { topic: "Work and occupations", id: 336, noun: "das Gehalt", plural: "Gehälter", english: "salary", pron: "das guhhalt" },
  { topic: "Work and occupations", id: 337, noun: "das Geld", plural: "—", english: "money", pron: "das guhld" },

  // Topic: Shopping and services (338 - 366)
  { topic: "Shopping and services", id: 338, noun: "das Geschäft", plural: "Geschäfte", english: "shop / business", pron: "das guhshehft" },
  { topic: "Shopping and services", id: 339, noun: "der Laden", plural: "Läden", english: "shop", pron: "dair laduhn" },
  { topic: "Shopping and services", id: 340, noun: "der Supermarkt", plural: "Supermärkte", english: "supermarket", pron: "dair supairmarkt" },
  { topic: "Shopping and services", id: 341, noun: "der Markt", plural: "Märkte", english: "market", pron: "dair markt" },
  { topic: "Shopping and services", id: 342, noun: "die Bäckerei", plural: "Bäckereien", english: "bakery", pron: "dee behckaireye" },
  { topic: "Shopping and services", id: 343, noun: "die Metzgerei", plural: "Metzgereien", english: "butcher's shop", pron: "dee muhttsgaireye" },
  { topic: "Shopping and services", id: 344, noun: "das Kaufhaus", plural: "Kaufhäuser", english: "department store", pron: "das kowfhows" },
  { topic: "Shopping and services", id: 345, noun: "das Einkaufszentrum", plural: "Einkaufszentren", english: "shopping center", pron: "das eyenkowfstsuhntrum" },
  { topic: "Shopping and services", id: 346, noun: "die Kasse", plural: "Kassen", english: "checkout / cash desk", pron: "dee kassuh" },
  { topic: "Shopping and services", id: 347, noun: "der Preis", plural: "Preise", english: "price", pron: "dair preyes" },
  { topic: "Shopping and services", id: 348, noun: "der Euro", plural: "Euro", english: "euro", pron: "dair oyro" },
  { topic: "Shopping and services", id: 349, noun: "der Cent", plural: "Cent", english: "cent", pron: "dair cuhnt" },
  { topic: "Shopping and services", id: 350, noun: "die Rechnung", plural: "Rechnungen", english: "bill / invoice", pron: "dee ruhkhnung" },
  { topic: "Shopping and services", id: 351, noun: "der Kassenbon", plural: "Kassenbons", english: "receipt", pron: "dair kassuhnbon" },
  { topic: "Shopping and services", id: 352, noun: "das Angebot", plural: "Angebote", english: "offer / special", pron: "das anguhbot" },
  { topic: "Shopping and services", id: 353, noun: "der Rabatt", plural: "Rabatte", english: "discount", pron: "dair rabatt" },
  { topic: "Shopping and services", id: 354, noun: "die Kreditkarte", plural: "Kreditkarten", english: "credit card", pron: "dee kruhditkartuh" },
  { topic: "Shopping and services", id: 355, noun: "die Bankkarte", plural: "Bankkarten", english: "bank card", pron: "dee bankkartuh" },
  { topic: "Shopping and services", id: 356, noun: "das Bargeld", plural: "—", english: "cash", pron: "das barguhld" },
  { topic: "Shopping and services", id: 357, noun: "die Bank", plural: "Banken", english: "bank", pron: "dee bank" },
  { topic: "Shopping and services", id: 358, noun: "das Konto", plural: "Konten", english: "account", pron: "das konto" },
  { topic: "Shopping and services", id: 359, noun: "der Geldautomat", plural: "Geldautomaten", english: "ATM", pron: "dair guhldowtomat" },
  { topic: "Shopping and services", id: 360, noun: "die Post", plural: "—", english: "post office / mail", pron: "dee posht" },
  { topic: "Shopping and services", id: 361, noun: "das Paket", plural: "Pakete", english: "parcel", pron: "das pakuht" },
  { topic: "Shopping and services", id: 362, noun: "der Brief", plural: "Briefe", english: "letter", pron: "dair breef" },
  { topic: "Shopping and services", id: 363, noun: "die Briefmarke", plural: "Briefmarken", english: "postage stamp", pron: "dee breefmarkuh" },
  { topic: "Shopping and services", id: 364, noun: "der Umschlag", plural: "Umschläge", english: "envelope", pron: "dair umshlag" },
  { topic: "Shopping and services", id: 365, noun: "der Friseurtermin", plural: "Friseurtermine", english: "hair appointment", pron: "dair frisoyrtairmin" },
  { topic: "Shopping and services", id: 366, noun: "die Reinigung", plural: "Reinigungen", english: "cleaning / dry cleaner's", pron: "dee reyenigung" },

  // Topic: Town and public places (367 - 398)
  { topic: "Town and public places", id: 367, noun: "die Stadt", plural: "Städte", english: "city", pron: "dee shtadt" },
  { topic: "Town and public places", id: 368, noun: "das Dorf", plural: "Dörfer", english: "village", pron: "das dorf" },
  { topic: "Town and public places", id: 369, noun: "das Land", plural: "Länder", english: "country", pron: "das land" },
  { topic: "Town and public places", id: 370, noun: "die Straße", plural: "Straßen", english: "street", pron: "dee shtrassuh" },
  { topic: "Town and public places", id: 371, noun: "der Weg", plural: "Wege", english: "way / path", pron: "dair fuhg" },
  { topic: "Town and public places", id: 372, noun: "der Platz", plural: "Plätze", english: "place / square", pron: "dair platts" },
  { topic: "Town and public places", id: 373, noun: "die Kreuzung", plural: "Kreuzungen", english: "intersection", pron: "dee kroytsung" },
  { topic: "Town and public places", id: 374, noun: "die Ampel", plural: "Ampeln", english: "traffic light", pron: "dee ampuhl" },
  { topic: "Town and public places", id: 375, noun: "die Brücke", plural: "Brücken", english: "bridge", pron: "dee brueckuh" },
  { topic: "Town and public places", id: 376, noun: "der Park", plural: "Parks", english: "park", pron: "dair park" },
  { topic: "Town and public places", id: 377, noun: "der Spielplatz", plural: "Spielplätze", english: "playground", pron: "dair shpeelplatts" },
  { topic: "Town and public places", id: 378, noun: "das Rathaus", plural: "Rathäuser", english: "town hall", pron: "das rathows" },
  { topic: "Town and public places", id: 379, noun: "das Amt", plural: "Ämter", english: "public office", pron: "das amt" },
  { topic: "Town and public places", id: 380, noun: "die Polizei", plural: "—", english: "police", pron: "dee politseye" },
  { topic: "Town and public places", id: 381, noun: "die Feuerwehr", plural: "Feuerwehren", english: "fire brigade", pron: "dee foyairfuhhr" },
  { topic: "Town and public places", id: 382, noun: "die Kirche", plural: "Kirchen", english: "church", pron: "dee kirkhuh" },
  { topic: "Town and public places", id: 383, noun: "die Moschee", plural: "Moscheen", english: "mosque", pron: "dee moshuhuh" },
  { topic: "Town and public places", id: 384, noun: "das Museum", plural: "Museen", english: "museum", pron: "das musoym" },
  { topic: "Town and public places", id: 385, noun: "das Theater", plural: "Theater", english: "theater", pron: "das thuhatair" },
  { topic: "Town and public places", id: 386, noun: "das Kino", plural: "Kinos", english: "cinema", pron: "das kino" },
  { topic: "Town and public places", id: 387, noun: "die Bibliothek", plural: "Bibliotheken", english: "library", pron: "dee bibliothuhk" },
  { topic: "Town and public places", id: 388, noun: "das Restaurant", plural: "Restaurants", english: "restaurant", pron: "das ruhshtowrant" },
  { topic: "Town and public places", id: 389, noun: "das Café", plural: "Cafés", english: "café", pron: "das café" },
  { topic: "Town and public places", id: 390, noun: "die Bar", plural: "Bars", english: "bar", pron: "dee bar" },
  { topic: "Town and public places", id: 391, noun: "das Hotel", plural: "Hotels", english: "hotel", pron: "das hotuhl" },
  { topic: "Town and public places", id: 392, noun: "die Rezeption", plural: "Rezeptionen", english: "reception desk", pron: "dee ruhtsuhption" },
  { topic: "Town and public places", id: 393, noun: "das Schwimmbad", plural: "Schwimmbäder", english: "swimming pool", pron: "das shfimmbad" },
  { topic: "Town and public places", id: 394, noun: "das Stadion", plural: "Stadien", english: "stadium", pron: "das shtadion" },
  { topic: "Town and public places", id: 395, noun: "der Bahnhof", plural: "Bahnhöfe", english: "train station", pron: "dair bahnhof" },
  { topic: "Town and public places", id: 396, noun: "die Haltestelle", plural: "Haltestellen", english: "stop / station", pron: "dee haltuhshtuhlluh" },
  { topic: "Town and public places", id: 397, noun: "der Flughafen", plural: "Flughäfen", english: "airport", pron: "dair flughafuhn" },
  { topic: "Town and public places", id: 398, noun: "der Hafen", plural: "Häfen", english: "harbor", pron: "dair hafuhn" },

  // Topic: Transport and travel (399 - 432)
  { topic: "Transport and travel", id: 399, noun: "die Reise", plural: "Reisen", english: "journey / trip", pron: "dee reyesuh" },
  { topic: "Transport and travel", id: 400, noun: "der Urlaub", plural: "Urlaube", english: "vacation", pron: "dair urlowb" },
  { topic: "Transport and travel", id: 401, noun: "das Auto", plural: "Autos", english: "car", pron: "das owto" },
  { topic: "Transport and travel", id: 402, noun: "der Wagen", plural: "Wagen", english: "car / carriage", pron: "dair faguhn" },
  { topic: "Transport and travel", id: 403, noun: "der Bus", plural: "Busse", english: "bus", pron: "dair bus" },
  { topic: "Transport and travel", id: 404, noun: "die Straßenbahn", plural: "Straßenbahnen", english: "tram", pron: "dee shtrassuhnbahn" },
  { topic: "Transport and travel", id: 405, noun: "die U-Bahn", plural: "U-Bahnen", english: "subway", pron: "dee u-bahn" },
  { topic: "Transport and travel", id: 406, noun: "die S-Bahn", plural: "S-Bahnen", english: "city train", pron: "dee s-bahn" },
  { topic: "Transport and travel", id: 407, noun: "der Zug", plural: "Züge", english: "train", pron: "dair tsug" },
  { topic: "Transport and travel", id: 408, noun: "das Taxi", plural: "Taxis", english: "taxi", pron: "das taxi" },
  { topic: "Transport and travel", id: 409, noun: "das Fahrrad", plural: "Fahrräder", english: "bicycle", pron: "das fahrrad" },
  { topic: "Transport and travel", id: 410, noun: "das Motorrad", plural: "Motorräder", english: "motorcycle", pron: "das motorrad" },
  { topic: "Transport and travel", id: 411, noun: "das Flugzeug", plural: "Flugzeuge", english: "airplane", pron: "das flugtsoyg" },
  { topic: "Transport and travel", id: 412, noun: "das Schiff", plural: "Schiffe", english: "ship", pron: "das shiff" },
  { topic: "Transport and travel", id: 413, noun: "die Fahrkarte", plural: "Fahrkarten", english: "ticket", pron: "dee fahrkartuh" },
  { topic: "Transport and travel", id: 414, noun: "das Ticket", plural: "Tickets", english: "ticket", pron: "das tickuht" },
  { topic: "Transport and travel", id: 415, noun: "der Fahrplan", plural: "Fahrpläne", english: "timetable", pron: "dair fahrplan" },
  { topic: "Transport and travel", id: 416, noun: "die Abfahrt", plural: "Abfahrten", english: "departure", pron: "dee abfahrt" },
  { topic: "Transport and travel", id: 417, noun: "die Ankunft", plural: "Ankünfte", english: "arrival", pron: "dee ankunft" },
  { topic: "Transport and travel", id: 418, noun: "das Gleis", plural: "Gleise", english: "platform / track", pron: "das gleyes" },
  { topic: "Transport and travel", id: 419, noun: "der Bahnsteig", plural: "Bahnsteige", english: "platform", pron: "dair bahnshteyeg" },
  { topic: "Transport and travel", id: 420, noun: "der Ausgang", plural: "Ausgänge", english: "exit", pron: "dair owsgang" },
  { topic: "Transport and travel", id: 421, noun: "der Eingang", plural: "Eingänge", english: "entrance", pron: "dair eyengang" },
  { topic: "Transport and travel", id: 422, noun: "die Richtung", plural: "Richtungen", english: "direction", pron: "dee rikhtung" },
  { topic: "Transport and travel", id: 423, noun: "die Fahrt", plural: "Fahrten", english: "ride / journey", pron: "dee fahrt" },
  { topic: "Transport and travel", id: 424, noun: "der Flug", plural: "Flüge", english: "flight", pron: "dair flug" },
  { topic: "Transport and travel", id: 425, noun: "der Pass", plural: "Pässe", english: "passport", pron: "dair pass" },
  { topic: "Transport and travel", id: 426, noun: "der Ausweis", plural: "Ausweise", english: "identity card", pron: "dair owsfeyes" },
  { topic: "Transport and travel", id: 427, noun: "das Visum", plural: "Visa", english: "visa", pron: "das fisum" },
  { topic: "Transport and travel", id: 428, noun: "die Grenze", plural: "Grenzen", english: "border", pron: "dee gruhntsuh" },
  { topic: "Transport and travel", id: 429, noun: "die Tankstelle", plural: "Tankstellen", english: "gas station", pron: "dee tankshtuhlluh" },
  { topic: "Transport and travel", id: 430, noun: "das Benzin", plural: "—", english: "gasoline", pron: "das buhntsin" },
  { topic: "Transport and travel", id: 431, noun: "der Verkehr", plural: "—", english: "traffic", pron: "dair fairkuhhr" },
  { topic: "Transport and travel", id: 432, noun: "der Stau", plural: "Staus", english: "traffic jam", pron: "dair shtow" },

  // Topic: Time, calendar, and events (433 - 474)
  { topic: "Time, calendar, and events", id: 433, noun: "die Zeit", plural: "Zeiten", english: "time", pron: "dee tseyet" },
  { topic: "Time, calendar, and events", id: 434, noun: "die Sekunde", plural: "Sekunden", english: "second", pron: "dee suhkunduh" },
  { topic: "Time, calendar, and events", id: 435, noun: "die Minute", plural: "Minuten", english: "minute", pron: "dee minutuh" },
  { topic: "Time, calendar, and events", id: 436, noun: "die Stunde", plural: "Stunden", english: "hour", pron: "dee shtunduh" },
  { topic: "Time, calendar, and events", id: 437, noun: "der Tag", plural: "Tage", english: "day", pron: "dair tag" },
  { topic: "Time, calendar, and events", id: 438, noun: "die Woche", plural: "Wochen", english: "week", pron: "dee fokhuh" },
  { topic: "Time, calendar, and events", id: 439, noun: "das Wochenende", plural: "Wochenenden", english: "weekend", pron: "das fokhuhnuhnduh" },
  { topic: "Time, calendar, and events", id: 440, noun: "der Monat", plural: "Monate", english: "month", pron: "dair monat" },
  { topic: "Time, calendar, and events", id: 441, noun: "das Jahr", plural: "Jahre", english: "year", pron: "das yahr" },
  { topic: "Time, calendar, and events", id: 442, noun: "der Morgen", plural: "Morgen", english: "morning", pron: "dair morguhn" },
  { topic: "Time, calendar, and events", id: 443, noun: "der Vormittag", plural: "Vormittage", english: "late morning", pron: "dair formittag" },
  { topic: "Time, calendar, and events", id: 444, noun: "der Mittag", plural: "Mittage", english: "noon", pron: "dair mittag" },
  { topic: "Time, calendar, and events", id: 445, noun: "der Nachmittag", plural: "Nachmittage", english: "afternoon", pron: "dair nakhmittag" },
  { topic: "Time, calendar, and events", id: 446, noun: "der Abend", plural: "Abende", english: "evening", pron: "dair abuhnd" },
  { topic: "Time, calendar, and events", id: 447, noun: "die Nacht", plural: "Nächte", english: "night", pron: "dee nakht" },
  { topic: "Time, calendar, and events", id: 448, noun: "der Montag", plural: "Montage", english: "Monday", pron: "dair montag" },
  { topic: "Time, calendar, and events", id: 449, noun: "der Dienstag", plural: "Dienstage", english: "Tuesday", pron: "dair deenshtag" },
  { topic: "Time, calendar, and events", id: 450, noun: "der Mittwoch", plural: "Mittwoche", english: "Wednesday", pron: "dair mittfokh" },
  { topic: "Time, calendar, and events", id: 451, noun: "der Donnerstag", plural: "Donnerstage", english: "Thursday", pron: "dair donnairshtag" },
  { topic: "Time, calendar, and events", id: 452, noun: "der Freitag", plural: "Freitage", english: "Friday", pron: "dair freyetag" },
  { topic: "Time, calendar, and events", id: 453, noun: "der Samstag", plural: "Samstage", english: "Saturday", pron: "dair samshtag" },
  { topic: "Time, calendar, and events", id: 454, noun: "der Sonntag", plural: "Sonntage", english: "Sunday", pron: "dair sonntag" },
  { topic: "Time, calendar, and events", id: 455, noun: "der Januar", plural: "—", english: "January", pron: "dair yanuar" },
  { topic: "Time, calendar, and events", id: 456, noun: "der Februar", plural: "—", english: "February", pron: "dair fuhbruar" },
  { topic: "Time, calendar, and events", id: 457, noun: "der März", plural: "—", english: "March", pron: "dair mehrts" },
  { topic: "Time, calendar, and events", id: 458, noun: "der April", plural: "—", english: "April", pron: "dair april" },
  { topic: "Time, calendar, and events", id: 459, noun: "der Mai", plural: "—", english: "May", pron: "dair mai" },
  { topic: "Time, calendar, and events", id: 460, noun: "der Juni", plural: "—", english: "June", pron: "dair yuni" },
  { topic: "Time, calendar, and events", id: 461, noun: "der Juli", plural: "—", english: "July", pron: "dair yuli" },
  { topic: "Time, calendar, and events", id: 462, noun: "der August", plural: "—", english: "August", pron: "dair owgusht" },
  { topic: "Time, calendar, and events", id: 463, noun: "der September", plural: "—", english: "September", pron: "dair suhptuhmbair" },
  { topic: "Time, calendar, and events", id: 464, noun: "der Oktober", plural: "—", english: "October", pron: "dair oktobair" },
  { topic: "Time, calendar, and events", id: 465, noun: "der November", plural: "—", english: "November", pron: "dair nofuhmbair" },
  { topic: "Time, calendar, and events", id: 466, noun: "der Dezember", plural: "—", english: "December", pron: "dair duhtsuhmbair" },
  { topic: "Time, calendar, and events", id: 467, noun: "das Datum", plural: "Daten", english: "date", pron: "das datum" },
  { topic: "Time, calendar, and events", id: 468, noun: "der Kalender", plural: "Kalender", english: "calendar", pron: "dair kaluhndair" },
  { topic: "Time, calendar, and events", id: 469, noun: "die Ferien", plural: "—", english: "holidays", pron: "dee faireen" },
  { topic: "Time, calendar, and events", id: 470, noun: "das Fest", plural: "Feste", english: "celebration / festival", pron: "das fuhsht" },
  { topic: "Time, calendar, and events", id: 471, noun: "die Party", plural: "Partys", english: "party", pron: "dee party" },
  { topic: "Time, calendar, and events", id: 472, noun: "die Hochzeit", plural: "Hochzeiten", english: "wedding", pron: "dee hokhtseyet" },
  { topic: "Time, calendar, and events", id: 473, noun: "die Einladung", plural: "Einladungen", english: "invitation", pron: "dee eyenladung" },
  { topic: "Time, calendar, and events", id: 474, noun: "das Geschenk", plural: "Geschenke", english: "gift", pron: "das guhshuhnk" },

  // Topic: Weather and nature (475 - 508)
  { topic: "Weather and nature", id: 475, noun: "das Wetter", plural: "—", english: "weather", pron: "das fuhttair" },
  { topic: "Weather and nature", id: 476, noun: "die Sonne", plural: "Sonnen", english: "sun", pron: "dee sonnuh" },
  { topic: "Weather and nature", id: 477, noun: "der Regen", plural: "—", english: "rain", pron: "dair ruhguhn" },
  { topic: "Weather and nature", id: 478, noun: "der Schnee", plural: "—", english: "snow", pron: "dair shnuhuh" },
  { topic: "Weather and nature", id: 479, noun: "der Wind", plural: "Winde", english: "wind", pron: "dair find" },
  { topic: "Weather and nature", id: 480, noun: "die Wolke", plural: "Wolken", english: "cloud", pron: "dee folkuh" },
  { topic: "Weather and nature", id: 481, noun: "der Himmel", plural: "—", english: "sky", pron: "dair himmuhl" },
  { topic: "Weather and nature", id: 482, noun: "die Luft", plural: "—", english: "air", pron: "dee luft" },
  { topic: "Weather and nature", id: 483, noun: "die Temperatur", plural: "Temperaturen", english: "temperature", pron: "dee tuhmpairatur" },
  { topic: "Weather and nature", id: 484, noun: "der Grad", plural: "Grade", english: "degree", pron: "dair grad" },
  { topic: "Weather and nature", id: 485, noun: "der Frühling", plural: "Frühlinge", english: "spring", pron: "dair fruehling" },
  { topic: "Weather and nature", id: 486, noun: "der Sommer", plural: "Sommer", english: "summer", pron: "dair sommair" },
  { topic: "Weather and nature", id: 487, noun: "der Herbst", plural: "Herbste", english: "autumn", pron: "dair hairbsht" },
  { topic: "Weather and nature", id: 488, noun: "der Winter", plural: "Winter", english: "winter", pron: "dair fintair" },
  { topic: "Weather and nature", id: 489, noun: "die Natur", plural: "—", english: "nature", pron: "dee natur" },
  { topic: "Weather and nature", id: 490, noun: "der Baum", plural: "Bäume", english: "tree", pron: "dair bowm" },
  { topic: "Weather and nature", id: 491, noun: "die Blume", plural: "Blumen", english: "flower", pron: "dee blumuh" },
  { topic: "Weather and nature", id: 492, noun: "das Gras", plural: "Gräser", english: "grass", pron: "das gras" },
  { topic: "Weather and nature", id: 493, noun: "der Wald", plural: "Wälder", english: "forest", pron: "dair fald" },
  { topic: "Weather and nature", id: 494, noun: "der Berg", plural: "Berge", english: "mountain", pron: "dair bairg" },
  { topic: "Weather and nature", id: 495, noun: "der See", plural: "Seen", english: "lake", pron: "dair suhuh" },
  { topic: "Weather and nature", id: 496, noun: "das Meer", plural: "Meere", english: "sea", pron: "das muhair" },
  { topic: "Weather and nature", id: 497, noun: "der Fluss", plural: "Flüsse", english: "river", pron: "dair fluss" },
  { topic: "Weather and nature", id: 498, noun: "der Strand", plural: "Strände", english: "beach", pron: "dair shtrand" },
  { topic: "Weather and nature", id: 499, noun: "die Insel", plural: "Inseln", english: "island", pron: "dee insuhl" },
  { topic: "Weather and nature", id: 500, noun: "das Tier", plural: "Tiere", english: "animal", pron: "das teer" },
  { topic: "Weather and nature", id: 501, noun: "der Hund", plural: "Hunde", english: "dog", pron: "dair hund" },
  { topic: "Weather and nature", id: 502, noun: "die Katze", plural: "Katzen", english: "cat", pron: "dee kattsuh" },
  { topic: "Weather and nature", id: 503, noun: "der Vogel", plural: "Vögel", english: "bird", pron: "dair foguhl" },
  { topic: "Weather and nature", id: 504, noun: "das Pferd", plural: "Pferde", english: "horse", pron: "das pfaird" },
  { topic: "Weather and nature", id: 505, noun: "die Kuh", plural: "Kühe", english: "cow", pron: "dee kuh" },
  { topic: "Weather and nature", id: 506, noun: "das Schwein", plural: "Schweine", english: "pig", pron: "das shfeyen" },
  { topic: "Weather and nature", id: 507, noun: "das Schaf", plural: "Schafe", english: "sheep", pron: "das shaf" },
  { topic: "Weather and nature", id: 508, noun: "die Maus", plural: "Mäuse", english: "mouse", pron: "dee mows" },

  // Topic: Free time, media, and communication (509 - 536)
  { topic: "Free time, media, and communication", id: 509, noun: "die Freizeit", plural: "—", english: "free time", pron: "dee freyetseyet" },
  { topic: "Free time, media, and communication", id: 510, noun: "das Hobby", plural: "Hobbys", english: "hobby", pron: "das hobby" },
  { topic: "Free time, media, and communication", id: 511, noun: "der Sport", plural: "—", english: "sport", pron: "dair shport" },
  { topic: "Free time, media, and communication", id: 512, noun: "der Fußball", plural: "Fußbälle", english: "football / soccer ball", pron: "dair fussball" },
  { topic: "Free time, media, and communication", id: 513, noun: "der Tennisball", plural: "Tennisbälle", english: "tennis ball", pron: "dair tuhnnisball" },
  { topic: "Free time, media, and communication", id: 514, noun: "das Spiel", plural: "Spiele", english: "game", pron: "das shpeel" },
  { topic: "Free time, media, and communication", id: 515, noun: "der Ball", plural: "Bälle", english: "ball", pron: "dair ball" },
  { topic: "Free time, media, and communication", id: 516, noun: "die Musik", plural: "—", english: "music", pron: "dee musik" },
  { topic: "Free time, media, and communication", id: 517, noun: "das Lied", plural: "Lieder", english: "song", pron: "das leed" },
  { topic: "Free time, media, and communication", id: 518, noun: "der Film", plural: "Filme", english: "film", pron: "dair film" },
  { topic: "Free time, media, and communication", id: 519, noun: "die Sendung", plural: "Sendungen", english: "broadcast / program", pron: "dee suhndung" },
  { topic: "Free time, media, and communication", id: 520, noun: "die Nachricht", plural: "Nachrichten", english: "message / news item", pron: "dee nakhrikht" },
  { topic: "Free time, media, and communication", id: 521, noun: "die Zeitung", plural: "Zeitungen", english: "newspaper", pron: "dee tseyetung" },
  { topic: "Free time, media, and communication", id: 522, noun: "die Zeitschrift", plural: "Zeitschriften", english: "magazine", pron: "dee tseyechrift" },
  { topic: "Free time, media, and communication", id: 523, noun: "das Foto", plural: "Fotos", english: "photo", pron: "das foto" },
  { topic: "Free time, media, and communication", id: 524, noun: "die Kamera", plural: "Kameras", english: "camera", pron: "dee kamaira" },
  { topic: "Free time, media, and communication", id: 525, noun: "das Internet", plural: "—", english: "internet", pron: "das intairnuht" },
  { topic: "Free time, media, and communication", id: 526, noun: "die E-Mail", plural: "E-Mails", english: "email", pron: "dee uh-mail" },
  { topic: "Free time, media, and communication", id: 527, noun: "die Webseite", plural: "Webseiten", english: "website", pron: "dee fuhbseyetuh" },
  { topic: "Free time, media, and communication", id: 528, noun: "das Passwort", plural: "Passwörter", english: "password", pron: "das passfort" },
  { topic: "Free time, media, and communication", id: 529, noun: "der Briefkasten", plural: "Briefkästen", english: "mailbox", pron: "dair breefkashtuhn" },
  { topic: "Free time, media, and communication", id: 530, noun: "das Gespräch", plural: "Gespräche", english: "conversation", pron: "das guhshprehkh" },
  { topic: "Free time, media, and communication", id: 531, noun: "der Anruf", plural: "Anrufe", english: "phone call", pron: "dair anruf" },
  { topic: "Free time, media, and communication", id: 532, noun: "die Information", plural: "Informationen", english: "information", pron: "dee information" },
  { topic: "Free time, media, and communication", id: 533, noun: "die Hilfe", plural: "—", english: "help", pron: "dee hilfuh" },
  { topic: "Free time, media, and communication", id: 534, noun: "der Verein", plural: "Vereine", english: "club / association", pron: "dair faireyen" },
  { topic: "Free time, media, and communication", id: 535, noun: "die Mannschaft", plural: "Mannschaften", english: "team", pron: "dee mannshaft" },
  { topic: "Free time, media, and communication", id: 536, noun: "das Konzert", plural: "Konzerte", english: "concert", pron: "das kontsairt" },

  // Topic: Documents, countries, and general A1 nouns (537 - 577)
  { topic: "Documents, countries, and general A1 nouns", id: 537, noun: "das Formular", plural: "Formulare", english: "form", pron: "das formular" },
  { topic: "Documents, countries, and general A1 nouns", id: 538, noun: "die Unterschrift", plural: "Unterschriften", english: "signature", pron: "dee untairshrift" },
  { topic: "Documents, countries, and general A1 nouns", id: 539, noun: "die Anmeldung", plural: "Anmeldungen", english: "registration", pron: "dee anmuhldung" },
  { topic: "Documents, countries, and general A1 nouns", id: 540, noun: "die Abmeldung", plural: "Abmeldungen", english: "deregistration", pron: "dee abmuhldung" },
  { topic: "Documents, countries, and general A1 nouns", id: 541, noun: "die Gebühr", plural: "Gebühren", english: "fee", pron: "dee guhbuehr" },
  { topic: "Documents, countries, and general A1 nouns", id: 542, noun: "die Versicherung", plural: "Versicherungen", english: "insurance", pron: "dee fairsikhairung" },
  { topic: "Documents, countries, and general A1 nouns", id: 543, noun: "die Karte", plural: "Karten", english: "card / map", pron: "dee kartuh" },
  { topic: "Documents, countries, and general A1 nouns", id: 544, noun: "der Plan", plural: "Pläne", english: "plan / map", pron: "dair plan" },
  { topic: "Documents, countries, and general A1 nouns", id: 545, noun: "die Liste", plural: "Listen", english: "list", pron: "dee lishtuh" },
  { topic: "Documents, countries, and general A1 nouns", id: 546, noun: "die Nummer", plural: "Nummern", english: "number", pron: "dee nummair" },
  { topic: "Documents, countries, and general A1 nouns", id: 547, noun: "die Ecke", plural: "Ecken", english: "corner", pron: "dee uhckuh" },
  { topic: "Documents, countries, and general A1 nouns", id: 548, noun: "die Mitte", plural: "Mitten", english: "middle", pron: "dee mittuh" },
  { topic: "Documents, countries, and general A1 nouns", id: 549, noun: "der Anfang", plural: "Anfänge", english: "beginning", pron: "dair anfang" },
  { topic: "Documents, countries, and general A1 nouns", id: 550, noun: "das Ende", plural: "Enden", english: "end", pron: "das uhnduh" },
  { topic: "Documents, countries, and general A1 nouns", id: 551, noun: "die Seite", plural: "Seiten", english: "page / side", pron: "dee seyetuh" },
  { topic: "Documents, countries, and general A1 nouns", id: 552, noun: "der Teil", plural: "Teile", english: "part", pron: "dair teyel" },
  { topic: "Documents, countries, and general A1 nouns", id: 553, noun: "das Stück", plural: "Stücke", english: "piece", pron: "das shtueck" },
  { topic: "Documents, countries, and general A1 nouns", id: 554, noun: "die Sache", plural: "Sachen", english: "thing / matter", pron: "dee sakhuh" },
  { topic: "Documents, countries, and general A1 nouns", id: 555, noun: "das Ding", plural: "Dinge", english: "thing", pron: "das ding" },
  { topic: "Documents, countries, and general A1 nouns", id: 556, noun: "das Problem", plural: "Probleme", english: "problem", pron: "das probluhm" },
  { topic: "Documents, countries, and general A1 nouns", id: 557, noun: "die Idee", plural: "Ideen", english: "idea", pron: "dee iduhuh" },
  { topic: "Documents, countries, and general A1 nouns", id: 558, noun: "der Wunsch", plural: "Wünsche", english: "wish", pron: "dair funsh" },
  { topic: "Documents, countries, and general A1 nouns", id: 559, noun: "die Angst", plural: "Ängste", english: "fear", pron: "dee angsht" },
  { topic: "Documents, countries, and general A1 nouns", id: 560, noun: "die Freude", plural: "Freuden", english: "joy", pron: "dee froyduh" },
  { topic: "Documents, countries, and general A1 nouns", id: 561, noun: "das Glück", plural: "—", english: "luck / happiness", pron: "das glueck" },
  { topic: "Documents, countries, and general A1 nouns", id: 562, noun: "der Spaß", plural: "—", english: "fun", pron: "dair shpass" },
  { topic: "Documents, countries, and general A1 nouns", id: 563, noun: "die Liebe", plural: "—", english: "love", pron: "dee leebuh" },
  { topic: "Documents, countries, and general A1 nouns", id: 564, noun: "das Leben", plural: "—", english: "life", pron: "das luhbuhn" },
  { topic: "Documents, countries, and general A1 nouns", id: 565, noun: "die Welt", plural: "Welten", english: "world", pron: "dee fuhlt" },
  { topic: "Documents, countries, and general A1 nouns", id: 566, noun: "die Heimat", plural: "—", english: "home country / homeland", pron: "dee heyemat" },
  { topic: "Documents, countries, and general A1 nouns", id: 567, noun: "die Nationalität", plural: "Nationalitäten", english: "nationality", pron: "dee nationaliteht" },
  { topic: "Documents, countries, and general A1 nouns", id: 568, noun: "der Deutsche", plural: "Deutschen", english: "German man", pron: "dair doychuh" },
  { topic: "Documents, countries, and general A1 nouns", id: 569, noun: "die Deutsche", plural: "Deutschen", english: "German woman", pron: "dee doychuh" },
  { topic: "Documents, countries, and general A1 nouns", id: 570, noun: "das Deutschland", plural: "—", english: "Germany", pron: "das doychland" },
  { topic: "Documents, countries, and general A1 nouns", id: 571, noun: "die Schweiz", plural: "—", english: "Switzerland", pron: "dee shfeyets" },
  { topic: "Documents, countries, and general A1 nouns", id: 572, noun: "das Österreich", plural: "—", english: "Austria", pron: "das urshtairreyekh" },
  { topic: "Documents, countries, and general A1 nouns", id: 573, noun: "das England", plural: "—", english: "England", pron: "das uhngland" },
  { topic: "Documents, countries, and general A1 nouns", id: 574, noun: "das Frankreich", plural: "—", english: "France", pron: "das frankreyekh" },
  { topic: "Documents, countries, and general A1 nouns", id: 575, noun: "das Italien", plural: "—", english: "Italy", pron: "das italeen" },
  { topic: "Documents, countries, and general A1 nouns", id: 576, noun: "das Spanien", plural: "—", english: "Spain", pron: "das shpaneen" },
  { topic: "Documents, countries, and general A1 nouns", id: 577, noun: "das Europa", plural: "—", english: "Europe", pron: "das oyropa" }
];

const processed = rawData.map(item => {
  const parts = item.noun.trim().split(' ');
  let article = '';
  let word = item.noun;
  if (['der', 'die', 'das'].includes(parts[0])) {
    article = parts[0];
    word = parts.slice(1).join(' ');
  }
  return {
    id: item.id,
    germanNoun: item.noun,
    article: article,
    word: word,
    plural: item.plural,
    english: item.english,
    pronunciation: item.pron,
    topic: item.topic
  };
});

const outputPath = path.join(process.cwd(), 'src', 'data', 'germanNounsData.json');
fs.writeFileSync(outputPath, JSON.stringify(processed, null, 2), 'utf-8');
console.log(`Successfully written ${processed.length} nouns to ${outputPath}`);
